services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - ./custom_components/up-bank:/config/custom_components/up-bank/
      - ha_recorder:/recorder
    restart: unless-stopped
    privileged: true
    ports:
      - '8124:8123'

volumes:
  ha_recorder: